stages:
  - setup
  - build
  - test
  - deploy
  - trigger_checkly

image: alpine

setup:
  stage: setup
  script:
    - apk add --update curl

build:
  stage: build
  script:
    - echo "This job builds something."

test:
  stage: test
  script:
    - echo "This job tests something. It will only run when all jobs in the"
    - echo "build stage are complete."

deploy:
  stage: deploy
  script:
    - echo "This job deploys something. It will only run when all jobs in the"
    - echo "test stage complete."

run_checkly:
  stage: trigger_checkly
  script:
   # Call Checkly trigger
    - curl "https://api-test.checklyhq.com/check-groups/4/trigger/${CHECKLY_TOKEN}" > ${PWD}/checkly.json
   # Exit with an error status if we find more than 0 "hasFailures: true" in the output
    - if [ $(grep -c \'"hasFailures":true\' $PWD/checkly.json) -ne 0 ]; then exit 1; fi
