stages:
  - build
  - test
  - deploy
  - trigger_checkly

image: curlimages/curl

build:
  stage: build
  script:
    - echo "Building..."

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying..."

run_checkly:
  stage: trigger_checkly
  script:
    - echo "Deployment finished."
    - echo $CHECKLY_TOKEN
    - echo ${CHECKLY_TOKEN}
    # Call Checkly trigger
    - curl https://api.checklyhq.com/checks/9b169dcb-a24a-475e-90b2-3bbc76c1b74a/trigger/$CHECKLY_TOKEN > ${PWD}/checkly.json
    - cat ${PWD}/checkly.json
    # Exit with an error status if we find more than 0 "hasFailures: true" in the output
    - if [ $(grep -c \'"hasFailures":true\' $PWD/checkly.json) -ne 0 ]; then exit 1; fi
